services:
  discord:
    image: ghcr.io/upcraftlp/rtuuy:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres/${DATABASE_NAME:-rtuuy}
    env_file:
      - .env
    networks:
      - internal

  postgres:
    image: docker.io/library/postgres:17-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:?database user required}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?database password required}
      POSTGRES_DB: ${DATABASE_NAME:-winterjam-mc-link}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
