services:
  db:
    image: docker.io/library/postgres:17-alpine
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-rtuuy}
      POSTGRES_USER: ${DATABASE_USERNAME:-rtuuy}
      POSTGRES_PASSWORD: ${DATABASE_PASWORD:-1a60250b-e319-4c25-a6f7-1b8f78f06f70}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
