services:
  db:
    image: docker.io/library/postgres:17-alpine
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: winterjam
      POSTGRES_USER: winterjam
      POSTGRES_PASSWORD: b55826c5-2273-4130-82b8-0116eeef045a
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
